import type { Metadata } from "next";
import "./globals.css";

import Header from "./Layout/Header";
import Footer from "./Layout/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Header />
        <div className="bg-white h-screen">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
